import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";

import LayoutWrapper from "./layout/LayoutWrapper";
import NextAuthProvider from "./provider/NextAuthProvider";
import QueryProvider from "./provider/QueryProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Assessment",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NextAuthProvider>
          <QueryProvider>
            <Toaster />
            <LayoutWrapper>{children}</LayoutWrapper>
          </QueryProvider>
        </NextAuthProvider>
      </body>
    </html>
  );
}
