import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
// import NextAuthProvider fro@/app/provider/NextAuthProviderder";
// import QueryProvider fro@/app/provider/QueryProviderder";
// import QueryProvider from "../";
import LayoutWrapper from "./layout/LayoutWrapper";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Assessment",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NextAuthProvider>
          <QueryProvider>
            <Toaster />
            <LayoutWrapper>{children}</LayoutWrapper>
          </QueryProvider>
        </NextAuthProvider>
      </body>
    </html>
  );
}
