import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import NextAuthProvider from "@/provider/NextAuthProvider";
import QueryProvider from "@/provider/QueryProvider";
import LayoutWrapper from "./layout/LayoutWrapper";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
                <NextAuthProvider>
         <QueryProvider>

          <Toaster />
          
          <LayoutWrapper>{children}</LayoutWrapper>
          </QueryProvider>
          </NextAuthProvider>
        {/* <Navbar/> */}
        {/* <Toaster/> */}
        {/* {children}
        <Footer/> */}
      </body>
    </html>
  );
}
